import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Burgermenu from "@/components/navbar/Burgermenu";
import Footer from "@/components/footer/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Fresh-lime",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="https://trashbagghost.com/cdn/shop/products/pixelcut-export-1663900688401.png?v=1663901329"
        />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Burgermenu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
